const mongoose = require('mongoose');

const technicalDetailsSchema = new mongoose.Schema({
  Brand: String,
  Manufacturer: String,
  Series: String,
  Colour: String,
  FormFactor: String,
  ItemHeight: String,
  ItemWidth: String,
  "Standing screen display size": String,
  ScreenResolution: String,
  ProductDimensions: String,
  Batteries: String,
  ItemModelNumber: String,
  ProcessorBrand: String,
  ProcessorType: String,
  ProcessorSpeed: String,
  ProcessorCount: String,
  RAMSize: String,
  MemoryTechnology: String,
  MaximumMemorySupported: String,
  HardDriveSize: String,
  HardDiskDescription: String,
  HardDriveInterface: String,
  AudioDetails: String,
  GraphicsChipsetBrand: String,
  GraphicsCardDescription: String,
  GraphicsRAMType: String,
  GraphicsCardInterface: String,
  ConnectivityType: String,
  NumberOfUSB2Ports: String,
  NumberOfUSB3Ports: String,
  Voltage: String,
  OpticalDriveType: String,
  PowerSource: String,
  HardwarePlatform: String,
  OperatingSystem: String,
  AverageBatteryStandbyLife: String,
  AverageBatteryLife: String,
  AreBatteriesIncluded: String,
  LithiumBatteryEnergyContent: String,
  NumberOfLithiumIonCells: String,
  IncludedComponents: String,
  CountryOfOrigin: String,
  ItemWeight: String,
  imageLinks: [String]
}, { _id: false });

const LaptopSchema = new mongoose.Schema({
  productName: { type: String, required: true },
  productLink: { type: String, required: true },
  cleanProductLink: { type: String, required: true },
  productId: { type: String, required: true, unique: true },
  sponsored: { type: String, enum: ['yes', 'no'], default: 'no' },
  badge: String,
  price: String,
  basePrice: String,
  rating: String,
  ratingsNumber: String,
  boughtPastMonth: String,
  technicalDetails: technicalDetailsSchema
});

module.exports = mongoose.model('Laptop', LaptopSchema);
